server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Exqress Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: http://af79ff7f7b96b4ceda2a71261c923a20-567584026.ap-northeast-2.elb.amazonaws.com/
          predicates:
            - Path=/user-service/user/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://af79ff7f7b96b4ceda2a71261c923a20-567584026.ap-northeast-2.elb.amazonaws.com/
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#            - Method=GET
#          filters:
#            - AuthenticationHeaderFilter
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: http://af79ff7f7b96b4ceda2a71261c923a20-567584026.ap-northeast-2.elb.amazonaws.com/
          predicates:
            - Path=/user-service/**
            - Method= GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}


        - id: delivery-service
          uri: http://ae9066c09904745a49fe7915b4a783cd-432689282.ap-northeast-2.elb.amazonaws.com/
          predicates:
            - Path=/delivery-service/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}



        - id: delivery-service
          uri: lb://DELIVERY-SERVICE
          predicates:
            - Path=/delivery-service/welcome
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/delivery-service/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh